# Generated by Django 2.2.6 on 2019-11-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteornet_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='height',
            new_name='elevation',
        ),
    ]
