# Generated by Django 2.2.6 on 2019-12-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteornet_server', '0003_auto_20191208_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='comment',
            new_name='info',
        ),
    ]
