# Generated by Django 2.2.9 on 2019-12-23 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteornet_server', '0004_auto_20191214_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='network_id',
            new_name='security_token',
        ),
    ]
