# Generated by Django 2.0.1 on 2018-05-02 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed Station', max_length=128)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature', models.FloatField(default=0.0)),
                ('humidity', models.FloatField(default=0.0)),
                ('disk_used', models.FloatField(default=0.0)),
                ('disk_cap', models.FloatField(default=0.0)),
            ],
        ),
    ]
